// apps/todo-react/template/src/App.jsx
import { useState } from "react";
import { beginTodoEdit, cancelTodoEdit, commitTodoEdit } from "./todo-editor.js";
import { addTodo, filterTodos, initialTodos, removeTodo, summarizeTodos, toggleTodo } from "./todo-store.js";

const filters = [
  { key: "all", label: "All" },
  { key: "active", label: "Active" },
  { key: "completed", label: "Completed" }
];

export default function App() {
  const [todos, setTodos] = useState(initialTodos);
  const [draft, setDraft] = useState("");
  const [filterKey, setFilterKey] = useState("all");
  const [editingId, setEditingId] = useState(null);
  const [editingDraft, setEditingDraft] = useState("");

  const summary = summarizeTodos(todos);
  const visibleTodos = filterTodos(todos, filterKey);

  function handleSubmit(event) {
    event.preventDefault();
    setTodos((current) => addTodo(current, draft));
    setDraft("");
  }

  function handleStartEdit(todo) {
    const next = beginTodoEdit(todo);
    setEditingId(next.editingId);
    setEditingDraft(next.draft);
  }

  function handleCancelEdit() {
    const next = cancelTodoEdit();
    setEditingId(next.editingId);
    setEditingDraft(next.draft);
  }

  function handleSaveEdit() {
    setTodos((current) => commitTodoEdit(current, editingId, editingDraft).todos);
    const next = cancelTodoEdit();
    setEditingId(next.editingId);
    setEditingDraft(next.draft);
  }

  function handleEditKeyDown(event) {
    if (event.key === "Enter") {
      event.preventDefault();
      handleSaveEdit();
      return;
    }

    if (event.key === "Escape") {
      event.preventDefault();
      handleCancelEdit();
    }
  }

  return (
    <main className="page-shell" data-bench="todo-app">
      <section className="hero-card">
        <p className="eyebrow">Benchmark Target</p>
        <h1>Todo Bench</h1>
        <p className="lead">
          Small todo app for local web QA runs, prompt-guided exploration, and bug-pack parity across frameworks.
        </p>
        <div className="summary-grid">
          <article className="summary-card">
            <span className="summary-label">Remaining</span>
            <strong>{summary.statusLine}</strong>
          </article>
          <article className="summary-card">
            <span className="summary-label">Progress</span>
            <strong>{summary.progressLine}</strong>
          </article>
        </div>
      </section>

      <section className="todo-card">
        <div className="todo-toolbar">
          <div>
            <p className="eyebrow">Todo Flow</p>
            <h2>Task board</h2>
          </div>
          <div className="filter-group" role="tablist" aria-label="Todo filters">
            {filters.map((filter) => (
              <button
                key={filter.key}
                type="button"
                data-filter={filter.key}
                className={filter.key === filterKey ? "filter-chip is-active" : "filter-chip"}
                onClick={() => setFilterKey(filter.key)}
              >
                {filter.label}
              </button>
            ))}
          </div>
        </div>

        <form className="composer" data-bench="composer" onSubmit={handleSubmit}>
          <label className="composer-field">
            <span className="sr-only">New task</span>
            <input
              type="text"
              data-bench="new-task-input"
              name="todoText"
              value={draft}
              placeholder="Add a task for the benchmark run"
              onChange={(event) => setDraft(event.target.value)}
            />
          </label>
          <button type="submit" className="primary-button" data-action="add">
            Add task
          </button>
        </form>

        <ul className="todo-list" aria-label="Todo items" data-bench="todo-list">
          {visibleTodos.map((todo) => (
            <li key={todo.id} data-todo-id={todo.id} className={todo.done ? "todo-item is-complete" : "todo-item"}>
              {editingId === todo.id ? (
                <>
                  <label className="todo-editor">
                    <span className="sr-only">Edit task</span>
                    <input
                      type="text"
                      data-bench="edit-task-input"
                      name={`edit-${todo.id}`}
                      value={editingDraft}
                      onChange={(event) => setEditingDraft(event.target.value)}
                      onKeyDown={handleEditKeyDown}
                    />
                  </label>
                  <div className="todo-actions">
                    <button
                      type="button"
                      className="primary-button action-button"
                      data-action="save"
                      onClick={handleSaveEdit}
                    >
                      Save
                    </button>
                    <button
                      type="button"
                      className="ghost-button action-button"
                      data-action="cancel"
                      onClick={handleCancelEdit}
                    >
                      Cancel
                    </button>
                  </div>
                </>
              ) : (
                <>
                  <label className="todo-main">
                    <input
                      type="checkbox"
                      data-action="toggle"
                      checked={todo.done}
                      onChange={() => setTodos((current) => toggleTodo(current, todo.id))}
                    />
                    <span>{todo.text}</span>
                  </label>
                  <div className="todo-actions">
                    <button
                      type="button"
                      className="ghost-button action-button"
                      data-action="edit"
                      onClick={() => handleStartEdit(todo)}
                    >
                      Edit
                    </button>
                    <button
                      type="button"
                      className="ghost-button action-button"
                      data-action="remove"
                      onClick={() => setTodos((current) => removeTodo(current, todo.id))}
                    >
                      Remove
                    </button>
                  </div>
                </>
              )}
            </li>
          ))}
        </ul>
      </section>
    </main>
  );
}

// apps/todo-angular/template/src/app/app.component.ts
import { CommonModule } from "@angular/common";
import { Component } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { beginTodoEdit, cancelTodoEdit, commitTodoEdit } from "./todo-editor";
import {
  addTodo,
  type FilterKey,
  filterTodos,
  initialTodos,
  removeTodo,
  summarizeTodos,
  type Todo,
  toggleTodo
} from "./todo-store";

const filters: Array<{ key: FilterKey; label: string }> = [
  { key: "all", label: "All" },
  { key: "active", label: "Active" },
  { key: "completed", label: "Completed" }
];

@Component({
  selector: "app-root",
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <main class="page-shell" data-bench="todo-app">
      <section class="hero-card">
        <p class="eyebrow">Benchmark Target</p>
        <h1>Todo Bench</h1>
        <p class="lead">
          Small todo app for local web QA runs, prompt-guided exploration, and bug-pack parity across frameworks.
        </p>
        <div class="summary-grid">
          <article class="summary-card">
            <span class="summary-label">Remaining</span>
            <strong>{{ summary.statusLine }}</strong>
          </article>
          <article class="summary-card">
            <span class="summary-label">Progress</span>
            <strong>{{ summary.progressLine }}</strong>
          </article>
        </div>
      </section>

      <section class="todo-card">
        <div class="todo-toolbar">
          <div>
            <p class="eyebrow">Todo Flow</p>
            <h2>Task board</h2>
          </div>
          <div class="filter-group" role="tablist" aria-label="Todo filters">
            <button
              *ngFor="let filter of filters"
              type="button"
              class="filter-chip"
              [class.is-active]="filter.key === filterKey"
              [attr.data-filter]="filter.key"
              (click)="setFilter(filter.key)"
            >
              {{ filter.label }}
            </button>
          </div>
        </div>

        <form class="composer" data-bench="composer" (ngSubmit)="handleSubmit()">
          <label class="composer-field">
            <span class="sr-only">New task</span>
            <input
              type="text"
              data-bench="new-task-input"
              name="todoText"
              [(ngModel)]="draft"
              placeholder="Add a task for the benchmark run"
            />
          </label>
          <button type="submit" class="primary-button" data-action="add">Add task</button>
        </form>

        <ul class="todo-list" aria-label="Todo items" data-bench="todo-list">
          <li
            *ngFor="let todo of visibleTodos; trackBy: trackByTodoId"
            class="todo-item"
            [class.is-complete]="todo.done"
            [attr.data-todo-id]="todo.id"
          >
            <ng-container *ngIf="editingId === todo.id; else readMode">
              <label class="todo-editor">
                <span class="sr-only">Edit task</span>
                <input
                  type="text"
                  data-bench="edit-task-input"
                  [name]="'edit-' + todo.id"
                  [(ngModel)]="editingDraft"
                  (keydown)="handleEditKeyDown($event)"
                />
              </label>
              <div class="todo-actions">
                <button type="button" class="primary-button action-button" data-action="save" (click)="handleSaveEdit()">
                  Save
                </button>
                <button type="button" class="ghost-button action-button" data-action="cancel" (click)="handleCancelEdit()">
                  Cancel
                </button>
              </div>
            </ng-container>

            <ng-template #readMode>
              <label class="todo-main">
                <input type="checkbox" data-action="toggle" [checked]="todo.done" (change)="handleToggle(todo.id)" />
                <span>{{ todo.text }}</span>
              </label>
              <div class="todo-actions">
                <button type="button" class="ghost-button action-button" data-action="edit" (click)="handleStartEdit(todo)">
                  Edit
                </button>
                <button type="button" class="ghost-button action-button" data-action="remove" (click)="handleRemove(todo.id)">
                  Remove
                </button>
              </div>
            </ng-template>
          </li>
        </ul>
      </section>
    </main>
  `
})
export class AppComponent {
  readonly filters = filters;
  todos: Todo[] = initialTodos;
  draft = "";
  filterKey: FilterKey = "all";
  editingId: string | null = null;
  editingDraft = "";

  get summary() {
    return summarizeTodos(this.todos);
  }

  get visibleTodos(): Todo[] {
    return filterTodos(this.todos, this.filterKey);
  }

  setFilter(filterKey: FilterKey): void {
    this.filterKey = filterKey;
  }

  handleSubmit(): void {
    this.todos = addTodo(this.todos, this.draft);
    this.draft = "";
  }

  handleToggle(id: string): void {
    this.todos = toggleTodo(this.todos, id);
  }

  handleRemove(id: string): void {
    this.todos = removeTodo(this.todos, id);
  }

  handleStartEdit(todo: Todo): void {
    const next = beginTodoEdit(todo);
    this.editingId = next.editingId;
    this.editingDraft = next.draft;
  }

  handleCancelEdit(): void {
    const next = cancelTodoEdit();
    this.editingId = next.editingId;
    this.editingDraft = next.draft;
  }

  handleSaveEdit(): void {
    const next = commitTodoEdit(this.todos, this.editingId, this.editingDraft);
    this.todos = next.todos;
    this.editingId = next.editingId;
    this.editingDraft = next.draft;
  }

  handleEditKeyDown(event: KeyboardEvent): void {
    if (event.key === "Enter") {
      event.preventDefault();
      this.handleSaveEdit();
      return;
    }

    if (event.key === "Escape") {
      event.preventDefault();
      this.handleCancelEdit();
    }
  }

  trackByTodoId(_index: number, todo: Todo): string {
    return todo.id;
  }
}
